# Change these first
owner: ory # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://www.ory.sh
  - name: Documentation
    url: https://www.ory.sh/docs
  - name: Kubernetes Helm Charts
    url: http://k8s.ory.sh/helm/
  - name: Ory Cloud (Staging)
    url: "$SECRET_STAGING_SITE"
  - name: Slack Invite Bot
    url: https://slack.ory.sh/
  - name: SQA Web API
    url: "$SECRET_SQA_WEB_SITE"
  - name: SQA API
    url: "$SECRET_SQA_SITE"
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Corsar API
    url: "https://corsar.ory.sh/orgs/ory/repos?__host=api.github.com&__proto=https&per_page=10&page=1"
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ory.sh
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ory Status
  introTitle: "Ory Builds Open Source Identity Infrastructure and Services."
  introMessage: This is Ory's real-time status page.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.ory.sh/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
commitMessages:
  commitAuthorName: "aeneasr"
  commitAuthorEmail: "3372410+aeneasr@users.noreply.github.com"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
